version: '3.9'

services:

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.develop
    volumes:
      - .:/usr/src/app
    ports:
      - 6350:80
    networks:
      - orchestrator_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
          
networks:
  orchestrator_net:
    driver: bridge
    name: orchestrator_net