version: '3.9'

services:
  auth_db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 6000:5432
    networks:
      - auth_net
    deploy:  
      resources:
        limits:
          cpus: '0.2'
          memory: 300M

  auth:
    build:
      context: .
      dockerfile: Dockerfile.develop
    volumes:
      - .:/usr/src/app
    ports:
      - 6050:80
    networks:
      - auth_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
    depends_on:
      auth_db:
        condition: service_started

networks:
  auth_net:
    driver: bridge
    name: auth_net